WHITESPACE = _{ " " | "\t" | "\n" }

statement = { create_stmt | select_stmt}

// create statement
create_stmt = { CREATE ~ NODE ~ label_clause ~ properties_clause? }

label_clause = { LABEL ~ "="? ~ ident }

properties_clause = { PROPERTIES ~ "="? ~ properties }
properties = { "(" ~ property ~ ("," ~ property)* ~ ")" }
property   = { ident ~ ":" ~ value }

value      = { string | number | boolean }

ident = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

number = @{ "-"? ~ ASCII_DIGIT+ }
string = @{ "\"" ~ (!"\"" ~ ANY)* ~ "\"" }
boolean = { TRUE | FALSE }

TRUE  = { "true" }
FALSE = { "false" }

CREATE     = { "CREATE" }
NODE       = { "NODE" }
LABEL      = { "LABEL" }
PROPERTIES = { "PROPERTIES" }

// select statement

select_stmt = { SELECT ~ variable_clause ~ FROM ~ relation_clause ~ where_clause?}

variable_clause = {ident ~ ("," ~ ident)*} 

relation_clause = {node_clause ~ ("-" ~ ident ~ "->" ~ node_clause)*}

node_clause = {ident ~ ":" ~ ident}

where_clause     = { WHERE ~ "(" ~ comparison ~ ("," ~ comparison)* ~ ")" }

comparison       = { ident ~ cmp_op ~ value }

cmp_op           = { ">=" | "<=" | "!=" | "=" | ">" | "<" }

SELECT = { "SELECT" }
FROM = { "FROM" }
WHERE = { "WHERE" }