select_stmt = {
    SELECT ~ variable_clause ~ FROM ~ relation_clause ~ where_clause?
}

variable_clause = { ident ~ ("," ~ ident)* }

relation_clause = {
    node_var_clause ~ ("-" ~ ident ~ "->" ~ node_var_clause)*
}

node_var_clause = { ident ~ ":" ~ ident }

where_clause = {
    WHERE ~ "(" ~ comparison ~ ("," ~ comparison)* ~ ")"
}

comparison = { ident ~ cmp_op ~ value }

cmp_op = { ">=" | "<=" | "!=" | "=" | ">" | "<" }
